postgresql:
  host: "localhost"
  port: "5432"
  user: "tmp"
  password: "test90123"
  database: "orders_db"

http_server:
  host: ""
  port: "8080"

kafka:
  brokers: "localhost:9092"
  topic: "orders"
  group_id: "order-service-group"